apiVersion: v1
kind: Service
metadata:
  name: do-kubernetes-sample-app
  namespace: default
  labels:
    app: do-kubernetes-sample-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-large"
spec:
  type: LoadBalancer
  selector:
    app: do-kubernetes-sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
